# Generated by Django 4.0.1 on 2022-01-07 03:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=15)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
